### ISSUE TITLE
Solo API Project コメント

### ISSUE THREAD

**Issue by Aik123** [ts-kouta/cc-api-solo#12]
@ts-kouta さん、プロジェクトお疲れ様でした！

短期間での開発お疲れ様でした 👏

いくつかコメントをさせていただきました！
（ひとつの意見なので、参考程度にしていただけると幸いです）

- README丁寧に書かれていて、素晴らしいです🙌（データベースのセットアップについての記述もあると尚良いですね）
- 全てのエンドポイントが正常に動いていて、エンドポイントの表現がRESTfulで良いですね👍
- [knexfile](https://github.com/ts-kouta/cc-api-solo/blob/fae35bdecab6652704f797b2ef5da3c5d8e97912/knexfile.js#L10-L12)は、環境変数を使用し、他の開発者が.env.localファイルを追加して個人の設定を反映できるようにしておくとより良さそうです！
- [cc-api-solo/src/server.js 23行目](https://github.com/ts-kouta/cc-api-solo/blob/fae35bdecab6652704f797b2ef5da3c5d8e97912/src/server.js#L23) constで変数宣言されていないので、注意しましょう👀
- ステータスコードを明示的に返すとよりRESTfulです。status code は DELETE や PATCH のそれぞれに対しも適切なコードがありますので、確認してみましょう（[DELETE](https://developer.mozilla.org/ja/docs/Web/HTTP/Methods/DELETE), [PATCH](https://developer.mozilla.org/ja/docs/Web/HTTP/Methods/PATCH)）
- new Date()などで、実際のアップデートの日時が自動で更新できるとより実践的ですね。
- `"test": "mocha test --exit"`をscriptsに追加するとテストが終了します👍

以上です！お疲れ様でした〜

**Comment by ts-kouta** [comment]
@Aik123 
コメント＆アドバイスありがとうございます！
データベースのセットアップやenvファイル、ステータスコード、Dateの件ご指摘のとおりかと思います。
constでの変数宣言の箇所は、変数宣言せずにreturnしたほうが良いという意味でしょうか？
もしくは、letで変数宣言すべきだったということですかね？（自分でも調べてみようと思います！）
テストが自動終了しない点なども原因を特定する体力がなかったためとても参考になりました！
ありがとうございました！

**Comment by Aik123** [comment]
質問ありがとうございます！

> [cc-api-solo/src/server.js 23行目](https://github.com/ts-kouta/cc-api-solo/blob/fae35bdecab6652704f797b2ef5da3c5d8e97912/src/server.js#L23) constで変数宣言されていないので、注意しましょう👀

もしかしたら単純な書き忘れかもとも思いましたが、setupExpressServerがconstを使用して宣言されていません。（変数キーワードがないまま宣言されています）
この場合、自動的にvarキーワードで宣言されたことになり、現在一般的に推奨されていない方法のため、明示的にconstで宣言した方が安全です〜という指摘でした！

**Comment by ts-kouta** [comment]
@Aik123
なるほどですね、、変数宣言失念しておりました。。
このままだとvarになってしまうと…ご指摘理解できました・・！
ありがとうございました！
